const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.resolve(__dirname, '..', 'assets');
const OUT_FILE = path.resolve(__dirname, '..', 'src', 'embedded-assets.ts');

const mime = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.mp3': 'audio/mpeg',
  '.m4a': 'audio/mp4',
  '.wav': 'audio/wav',
  '.ogg': 'audio/ogg',
  '.mp4': 'video/mp4',
  '.json': 'application/json',
  '.xml': 'application/xml',
  '.atlas': 'text/plain',
  '.svg': 'image/svg+xml',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2'
};

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  for (const e of entries) {
    const res = path.resolve(dir, e.name);
    if (e.isDirectory()) files = files.concat(walk(res));
    else files.push(res);
  }
  return files;
}

function relativeKey(file) {
  return path.relative(ASSETS_DIR, file).replace(/\\/g, '/');
}

function toDataURI(file) {
  const ext = path.extname(file).toLowerCase();
  const m = mime[ext] || 'application/octet-stream';
  const buf = fs.readFileSync(file);
  if (m.startsWith('text/') || ext === '.svg' || ext === '.atlas' || ext === '.json' || ext === '.xml') {
    // Try to keep text formats readable
    const text = buf.toString('utf8').replace(/`/g, '\\`');
    return `data:${m};charset=utf-8,${encodeURIComponent(text)}`;
  }
  return `data:${m};base64,${buf.toString('base64')}`;
}

function main() {
  if (!fs.existsSync(ASSETS_DIR)) {
    console.error('No assets directory found at', ASSETS_DIR);
    process.exit(1);
  }

  const files = walk(ASSETS_DIR);
  const entries = files.map((f) => {
    const key = relativeKey(f);
    try {
      const data = toDataURI(f);
      return `  "${key}": "${data}"`;
    } catch (e) {
      console.error('Failed to embed', f, e.message);
      return null;
    }
  }).filter(Boolean);

  const content = `// Auto-generated by scripts/embed-assets.js - do not edit\nexport default {\n${entries.join(',\n')}\n};\n`;

  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log('Wrote', OUT_FILE, 'with', entries.length, 'entries');
}

main();
